const types = {
  SET_CONTACTS_SEARCH_TERM: "SET_CONTACTS_SEARCH_TERM",
  SET_CONTACTS: "SET_CONTACTS",
  SET_CONTACT: "SET_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  SAVE_CONTACT: "SAVE_CONTACT"
};
export default types;
